name: Primeiro Workflow

on:
  push:

jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Primeiro Passo"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lista arquivos
        run: ls ${{ github.workspace }}
      - name: Status
        run: echo "Status ${{ job.status }}."
